### ISSUE TITLE
App Crashes after processing payment on ReadyUI

### ISSUE THREAD

**Issue by abbas-25** [HyperpayOpenSource/flutter-demo#2]
Here are the logs -

```
V/AudioManager(27482): querySoundEffectsEnabled...
I/flutter (27482): response code == 200
I/flutter (27482): decodedRes["id"] -  B10C4848787C0DEEE151E51465E7DB2E.uat01-vm-tx01
D/ZrHung.AppEyeUiProbe(27482): stop checker.
W/ActivityThread(27482): handleWindowVisibility: no activity for token android.os.BinderProxy@ca742bc
D/ZrHung.AppEyeUiProbe(27482): notify runnable to start.
V/ActivityThread(27482): Skipping new config:{1.0 405mcc870mnc [en_GB,ar_GB] ldltr sw360dp w360dp h730dp 480dpi nrml long port night finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 1080, 2190) mAppBounds=Rect(0, 90 - 1080, 2280) mWindowingMode=fullscreen mActivityType=undefined} nonFullScreen=0 suim:4 s.39}, config:{1.0 405mcc870mnc [en_GB,ar_GB] ldltr sw360dp w360dp h730dp 480dpi nrml long port night finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 1080, 2190) mAppBounds=Rect(0, 90 - 1080, 2280) mWindowingMode=fullscreen mActivityType=undefined} nonFullScreen=0 suim:4 s.39} for app:com.mosab.flutter_demo
V/ActivityThread(27482): callActivityOnCreate
I/HwPhoneWindow(27482): updateLayoutParamsColor false mSpecialSet=false, mForcedNavigationBarColor=false, navigationBarColor=0, mNavBarShow=false, mIsFloating=false
I/HwPhoneWindow(27482): updateLayoutParamsColor true mSpecialSet=false, mForcedNavigationBarColor=false, navigationBarColor=ff000000, mNavBarShow=false, mIsFloating=false
W/ab.flutter_dem(27482): Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (light greylist, reflection)
W/ab.flutter_dem(27482): Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (light greylist, reflection)
W/ab.flutter_dem(27482): Unknown chunk type '200'.
I/ab.flutter_dem(27482): The ClassLoaderContext is a special shared library.
I/chatty  (27482): uid=10018(com.mosab.flutter_demo) identical 1 line
I/ab.flutter_dem(27482): The ClassLoaderContext is a special shared library.
V/NativeCrypto(27482): Registering com/google/android/gms/org/conscrypt/NativeCrypto's 288 native methods...
W/ab.flutter_dem(27482): Accessing hidden method Ljava/security/spec/ECParameterSpec;->getCurveName()Ljava/lang/String; (light greylist, reflection)
I/ProviderInstaller(27482): Installed default security provider GmsCore_OpenSSL
D/ActivityThread(27482): add activity client record, r= ActivityRecord{94fc9d1 token=android.os.BinderProxy@ca742bc {com.mosab.flutter_demo/com.oppwa.mobile.connect.checkout.dialog.CheckoutActivity}} token= android.os.BinderProxy@ca742bc
D/TextView(27482): get Display Panel Type is : 0
D/ZrHung.AppEyeUiProbe(27482): notify runnable to start.
D/OpenGLRenderer(27482):   HWUI Binary is  enabled
I/HiTouch_HiTouchSensor(27482): enabledInPad = false,isPcCastMode = false
D/HiTouch_PressGestureDetector(27482): onAttached, package=com.mosab.flutter_demo, windowType=1, mHiTouchRestricted=false
D/mali_winsys(27482): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
I/ViewRootImpl(27482): jank_removeInvalidNode all the node in jank list is out of time
D/OpenGLRenderer(27482):   HWUI Binary is  enabled
W/InputMethodManager(27482): startInputReason = 1
W/ab.flutter_dem(27482): Accessing hidden field Ljava/net/Socket;->impl:Ljava/net/SocketImpl; (light greylist, reflection)
W/ab.flutter_dem(27482): Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (light greylist, linking)
W/ab.flutter_dem(27482): Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (light greylist, linking)
W/ab.flutter_dem(27482): Accessing hidden field Ljava/io/FileDescriptor;->descriptor:I (light greylist, JNI)
W/ab.flutter_dem(27482): Accessing hidden method Ldalvik/system/BlockGuard;->getThreadPolicy()Ldalvik/system/BlockGuard$Policy; (light greylist, linking)
W/ab.flutter_dem(27482): Accessing hidden method Ldalvik/system/BlockGuard$Policy;->onNetwork()V (light greylist, linking)
I/FLTAG_FM(27482): loadFeature class:com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
I/FLTAG_SFM(27482): getRequireClassLoader() succ ! className: com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
D/FeatureFactory(27482): loadFeature() : com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
D/FeatureFactory(27482): loadFeature() new IHwSplineOverScrollerEx()
D/HwSplineOverScrollerExImpl(27482): initSplineOverScrollerImpl paras: android.widget.OverScroller$SplineOverScroller@60a68b4,com.oppwa.mobile.connect.checkout.dialog.CheckoutActivity@8865dc1
D/HwSplineOverScrollerExImpl(27482): initSplineOverScrollerImpl: mScrollerVelocity is 0, value is 0
I/FLTAG_FM(27482): loadFeature class:com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
I/FLTAG_SFM(27482): getRequireClassLoader() succ ! className: com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
D/FeatureFactory(27482): loadFeature() : com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
D/FeatureFactory(27482): loadFeature() new IHwSplineOverScrollerEx()
D/HwSplineOverScrollerExImpl(27482): initSplineOverScrollerImpl paras: android.widget.OverScroller$SplineOverScroller@33f5c20,com.oppwa.mobile.connect.checkout.dialog.CheckoutActivity@8865dc1
D/HwSplineOverScrollerExImpl(27482): initSplineOverScrollerImpl: mScrollerVelocity is 0, value is 0
I/TextInputLayout(27482): EditText added is not a TextInputEditText. Please switch to using that class instead.
I/FLTAG_FM(27482): loadFeature class:com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
I/FLTAG_SFM(27482): getRequireClassLoader() succ ! className: com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
D/FeatureFactory(27482): loadFeature() : com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
D/FeatureFactory(27482): loadFeature() new IHwSplineOverScrollerEx()
D/HwSplineOverScrollerExImpl(27482): initSplineOverScrollerImpl paras: android.widget.OverScroller$SplineOverScroller@121334f,com.oppwa.mobile.connect.checkout.dialog.CheckoutActivity@8865dc1
D/HwSplineOverScrollerExImpl(27482): initSplineOverScrollerImpl: mScrollerVelocity is 0, value is 0
I/FLTAG_FM(27482): loadFeature class:com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
I/FLTAG_SFM(27482): getRequireClassLoader() succ ! className: com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
D/FeatureFactory(27482): loadFeature() : com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
D/FeatureFactory(27482): loadFeature() new IHwSplineOverScrollerEx()
D/HwSplineOverScrollerExImpl(27482): initSplineOverScrollerImpl paras: android.widget.OverScroller$SplineOverScroller@7e7b56b,com.oppwa.mobile.connect.checkout.dialog.CheckoutActivity@8865dc1
D/HwSplineOverScrollerExImpl(27482): initSplineOverScrollerImpl: mScrollerVelocity is 0, value is 0
I/TextInputLayout(27482): EditText added is not a TextInputEditText. Please switch to using that class instead.
I/chatty  (27482): uid=10018(com.mosab.flutter_demo) identical 3 lines
I/TextInputLayout(27482): EditText added is not a TextInputEditText. Please switch to using that class instead.
D/HwGalleryCacheManagerImpl(27482): mIsEffect:false
I/Choreographer(27482): Skipped 42 frames!  The application may be doing too much work on its main thread.
E/RecyclerView(27482): No adapter attached; skipping layout
I/ViewRootImpl(27482): jank_removeInvalidNode jank list is null
W/Settings(27482): Setting device_provisioned has moved from android.provider.Settings.Secure to android.provider.Settings.Global.
V/HiTouch_HiTouchSensor(27482): User setup is finished.
D/HwAutofillHelper(27482): recordCurrentInfo:0
D/HwAutofillHelper(27482): inputType = 524290
W/InputMethodManager(27482): startInputReason = 4
I/InputMethodManager(27482): showSoftInput
I/InputMethodManager(27482): mServedView =com.mosab.flutter_demo;view =com.mosab.flutter_demo;flags =0
I/HwSecImmHelper(27482): mSecurityInputMethodService is null
I/AssistStructure(27482): Flattened final assist data: 11196 bytes, containing 1 windows, 44 views
E/RecyclerView(27482): No adapter attached; skipping layout
D/DISK_CACHE(27482): Check creation date VISA
D/DISK_CACHE(27482): Prepare to delete 422934
W/InputMethodManager(27482): startInputReason = 3
W/IInputConnectionWrapper(27482): getExtractedText on inactive InputConnection
W/IInputConnectionWrapper(27482): getTextBeforeCursor on inactive InputConnection
W/InputMethodManager(27482): startInputReason = 3
W/IInputConnectionWrapper(27482): sendKeyEvent on inactive InputConnection
W/IInputConnectionWrapper(27482): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper(27482): getExtractedText on inactive InputConnection
W/IInputConnectionWrapper(27482): getTextBeforeCursor on inactive InputConnection
W/InputMethodManager(27482): startInputReason = 3
W/IInputConnectionWrapper(27482): sendKeyEvent on inactive InputConnection
W/IInputConnectionWrapper(27482): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper(27482): getExtractedText on inactive InputConnection
W/IInputConnectionWrapper(27482): getTextBeforeCursor on inactive InputConnection
W/InputMethodManager(27482): startInputReason = 3
W/IInputConnectionWrapper(27482): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper(27482): getExtractedText on inactive InputConnection
W/IInputConnectionWrapper(27482): getTextBeforeCursor on inactive InputConnection
W/InputMethodManager(27482): startInputReason = 3
W/IInputConnectionWrapper(27482): sendKeyEvent on inactive InputConnection
W/IInputConnectionWrapper(27482): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper(27482): getExtractedText on inactive InputConnection
W/IInputConnectionWrapper(27482): getTextBeforeCursor on inactive InputConnection
W/InputMethodManager(27482): startInputReason = 3
W/IInputConnectionWrapper(27482): sendKeyEvent on inactive InputConnection
W/IInputConnectionWrapper(27482): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper(27482): getExtractedText on inactive InputConnection
W/IInputConnectionWrapper(27482): getTextBeforeCursor on inactive InputConnection
W/InputMethodManager(27482): startInputReason = 3
W/IInputConnectionWrapper(27482): sendKeyEvent on inactive InputConnection
W/IInputConnectionWrapper(27482): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper(27482): getExtractedText on inactive InputConnection
W/IInputConnectionWrapper(27482): getTextBeforeCursor on inactive InputConnection
W/InputMethodManager(27482): startInputReason = 3
W/IInputConnectionWrapper(27482): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper(27482): getExtractedText on inactive InputConnection
W/IInputConnectionWrapper(27482): getTextBeforeCursor on inactive InputConnection
W/InputMethodManager(27482): startInputReason = 3
W/IInputConnectionWrapper(27482): sendKeyEvent on inactive InputConnection
W/IInputConnectionWrapper(27482): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper(27482): getExtractedText on inactive InputConnection
W/IInputConnectionWrapper(27482): getTextBeforeCursor on inactive InputConnection
W/InputMethodManager(27482): startInputReason = 3
W/IInputConnectionWrapper(27482): sendKeyEvent on inactive InputConnection
W/IInputConnectionWrapper(27482): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper(27482): getExtractedText on inactive InputConnection
W/IInputConnectionWrapper(27482): getTextBeforeCursor on inactive InputConnection
W/InputMethodManager(27482): startInputReason = 3
W/IInputConnectionWrapper(27482): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper(27482): getExtractedText on inactive InputConnection
W/IInputConnectionWrapper(27482): getTextBeforeCursor on inactive InputConnection
W/InputMethodManager(27482): startInputReason = 3
W/IInputConnectionWrapper(27482): sendKeyEvent on inactive InputConnection
W/IInputConnectionWrapper(27482): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper(27482): getExtractedText on inactive InputConnection
W/IInputConnectionWrapper(27482): getTextBeforeCursor on inactive InputConnection
W/InputMethodManager(27482): startInputReason = 3
W/IInputConnectionWrapper(27482): sendKeyEvent on inactive InputConnection
W/IInputConnectionWrapper(27482): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper(27482): getExtractedText on inactive InputConnection
W/IInputConnectionWrapper(27482): getTextBeforeCursor on inactive InputConnection
D/HwAutofillHelper(27482): recordCurrentInfo:0
D/HwAutofillHelper(27482): inputType = 528384
W/InputMethodManager(27482): startInputReason = 4
I/InputMethodManager(27482): showSoftInput
I/InputMethodManager(27482): mServedView =com.mosab.flutter_demo;view =com.mosab.flutter_demo;flags =0
I/HwSecImmHelper(27482): mSecurityInputMethodService is null
V/InputMethodManager(27482): Reporting focus gain, without startInput
W/InputMethodManager(27482): startInputReason = 3
V/InputMethodManager(27482): Reporting focus gain, without startInput
D/HwAutofillHelper(27482): recordCurrentInfo:0
D/HwAutofillHelper(27482): inputType = 524290
W/InputMethodManager(27482): startInputReason = 4
I/InputMethodManager(27482): showSoftInput
I/InputMethodManager(27482): mServedView =com.mosab.flutter_demo;view =com.mosab.flutter_demo;flags =0
I/HwSecImmHelper(27482): mSecurityInputMethodService is null
I/AssistStructure(27482): Flattened final assist data: 11300 bytes, containing 1 windows, 44 views
D/HwAutofillHelper(27482): recordCurrentInfo:0
D/HwAutofillHelper(27482): inputType = 2
W/InputMethodManager(27482): startInputReason = 4
I/InputMethodManager(27482): showSoftInput
I/InputMethodManager(27482): mServedView =com.mosab.flutter_demo;view =com.mosab.flutter_demo;flags =0
I/HwSecImmHelper(27482): mSecurityInputMethodService is null
I/ViewRootImpl(27482): jank_removeInvalidNode all the node in jank list is out of time
I/AssistStructure(27482): Flattened final assist data: 11316 bytes, containing 1 windows, 44 views
I/HwSecImmHelper(27482): mSecurityInputMethodService is null
E/RecyclerView(27482): No adapter attached; skipping layout
V/AudioManager(27482): playSoundEffect   effectType: 0
V/AudioManager(27482): querySoundEffectsEnabled...
W/InputMethodManager(27482): startInputReason = 3
E/        (27482): [ZeroHung]zrhung_get_config: Get config failed for wp[0x0008]
W/System  (27482): A resource failed to call end. 
I/chatty  (27482): uid=10018(com.mosab.flutter_demo) FinalizerDaemon identical 1 line
W/System  (27482): A resource failed to call end. 
W/IInputConnectionWrapper(27482): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper(27482): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper(27482): getExtractedText on inactive InputConnection
W/IInputConnectionWrapper(27482): getTextBeforeCursor on inactive InputConnection
W/ab.flutter_dem(27482): Accessing hidden method Ldalvik/system/CloseGuard;->close()V (light greylist, linking)
I/flutter (27482): SYNC
D/ZrHung.AppEyeUiProbe(27482): stop checker.
W/InputMethodManager(27482): startInputReason = 1
D/ZrHung.AppEyeUiProbe(27482): Current Activity:false
D/ZrHung.AppEyeUiProbe(27482): not watching, wait.
D/ZrHung.AppEyeUiProbe(27482): notify runnable to start.
D/ZrHung.AppEyeUiProbe(27482): restart watching
D/AndroidRuntime(27482): Shutting down VM
W/ab.flutter_dem(27482): Accessing hidden method Lcom/msic/qarth/PatchStore;->createDisableExceptionQarthFile(Ljava/lang/Throwable;)Z (blacklist, JNI)
E/ab.flutter_dem(27482): [qarth_debug:]  get PatchStore::createDisableExceptionQarthFile method fail.
E/AndroidRuntime(27482): FATAL EXCEPTION: main
E/AndroidRuntime(27482): Process: com.mosab.flutter_demo, PID: 27482
E/AndroidRuntime(27482): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(27482):        at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:139)
E/AndroidRuntime(27482):        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:238)
E/AndroidRuntime(27482):        at com.mosab.flutter_demo.MainActivity$1.run(MainActivity.java:92)
E/AndroidRuntime(27482):        at android.os.Handler.handleCallback(Handler.java:907)
E/AndroidRuntime(27482):        at android.os.Handler.dispatchMessage(Handler.java:105)
E/AndroidRuntime(27482):        at android.os.Looper.loop(Looper.java:216)
E/AndroidRuntime(27482):        at android.app.ActivityThread.main(ActivityThread.java:7625)
E/AndroidRuntime(27482):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(27482):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
E/AndroidRuntime(27482):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
I/Process (27482): Sending signal. PID: 27482 SIG: 9
Lost connection to device.
```

**Comment by bshbsh404** [comment]
@abbas-25 Were you able to solve the issue?

**Comment by nareshonly851** [comment]
@bshbsh404 
private Boolean methodCheckFlag = true;

 if (methodCheckFlag) {
                Result.success("success");
                methodCheckFlag = false;
  }
