### ISSUE TITLE
After add this code in MainActivity other plugging not working  

### ISSUE THREAD

**Issue by saprahits** [HyperpayOpenSource/flutter-demo#3]
`I/flutter (23095): PlatformException(already_active, Image picker is already active, null, null)
I/flutter (23095): 
I/flutter (23095): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582:7)
I/flutter (23095): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
I/flutter (23095): <asynchronous suspension>
I/flutter (23095): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
I/flutter (23095): #3      MethodChannelImagePicker.pickImagePath (package:image_picker_platform_interface/src/method_channel/method_channel_image_picker.dart:62:21)
I/flutter (23095): #4      MethodChannelImagePicker.pickImage (package:image_picker_platform_interface/src/method_channel/method_channel_image_picker.dart:30:25)
I/flutter (23095): #5      ImagePicker.getImage (package:image_picker/image_picker.dart:106:21)
I/flutter (23095): #6      _EditProfileState.getImage (package:graham/screens/Profile/sc_editProfile.dart:113:37)
I/flutter (23095): #7      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
I/flutter (23095): #8      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1111:38)
I/flutter (23095): #9      GestureRecognizer.invokeCallback (package`

**Comment by nareshonly851** [comment]
@saprahits 
 **super.onActivityResult(requestCode, resultCode, data)** add this line in onActivityResult method
